apiVersion: 2023-05-01
location: westeurope
name: abb09
properties:
  imageRegistryCredentials:
      - server: abb09.azurecr.io
        username: abb09
        password: password.registry

  containers:
  - name: abb09-front
    properties:
      image: abb09.azurecr.io/ab-front:latest
      resources:
        requests:
          cpu: 1
          memoryInGb: 1.5
      ports:
      - port: 8001
  - name: abb09-back
    properties:
      image: abb09.azurecr.io/ab-back:latest
      ports:
      - port: 8000
      resources:
        requests:
          cpu: 1
          memoryInGb: 1.5

  osType: Linux
  ipAddress:
    type: Public
    dnsNameLabel: abb09
    ports:
    - protocol: tcp
      port: 8001
    - protocol: tcp
      port: 8000

tags: {exampleTag: abb09}
type: Microsoft.ContainerInstance/containerGroups