version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.front
    ports:
      - "8001:8001"
    depends_on:
      - backend
    networks:
      - app_network

  backend:
    build:
      context: .
      dockerfile: Dockerfile.back
    ports:
      - "8000:8000"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
